# Generated by Django 4.2.3 on 2023-08-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientId', models.AutoField(primary_key=True, serialize=False)),
                ('ClientName', models.CharField(max_length=50, verbose_name='Имя')),
                ('ClientPhone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('ClientCar', models.CharField(max_length=100, verbose_name='Автомобиль')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
